import { TemplateConfig } from './template-renderer';

// 25 ATS Friendly Templates
const atsTemplates: TemplateConfig[] = [
  { id:'ats-1', name:'Clean Professional', category:'ats', atsScore:97, layout:'single', fonts:{heading:'Georgia, serif',body:'Arial, sans-serif'}, colors:{primary:'#2c3e50',secondary:'#34495e',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#ecf0f1'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','education','skills','certifications','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-2', name:'Executive', category:'ats', atsScore:95, layout:'single', fonts:{heading:'Cambria, serif',body:'Calibri, sans-serif'}, colors:{primary:'#1a237e',secondary:'#283593',text:'#212121',muted:'#555',bg:'#fff',accent:'#e8eaf6'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','education','skills','projects','certifications'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-3', name:'Corporate', category:'ats', atsScore:96, layout:'single', fonts:{heading:'Times New Roman, serif',body:'Arial, sans-serif'}, colors:{primary:'#1b5e20',secondary:'#2e7d32',text:'#1a1a1a',muted:'#444',bg:'#fff',accent:'#e8f5e9'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','education','skills','certifications','awards'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-4', name:'Modern ATS', category:'ats', atsScore:94, layout:'single', fonts:{heading:'Helvetica, sans-serif',body:'Helvetica, sans-serif'}, colors:{primary:'#6200ea',secondary:'#7c4dff',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#ede7f6'}, spacing:'normal', headerStyle:'split', sectionOrder:['summary','experience','skills','education','projects','certifications'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'dash' },
  { id:'ats-5', name:'Simple ATS', category:'ats', atsScore:98, layout:'single', fonts:{heading:'Arial, sans-serif',body:'Arial, sans-serif'}, colors:{primary:'#333',secondary:'#555',text:'#1a1a1a',muted:'#666',bg:'#fff',accent:'#f5f5f5'}, spacing:'compact', headerStyle:'left', sectionOrder:['summary','experience','education','skills','certifications'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-6', name:'Compact ATS', category:'ats', atsScore:96, layout:'single', fonts:{heading:'Verdana, sans-serif',body:'Verdana, sans-serif'}, colors:{primary:'#004d40',secondary:'#00695c',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#e0f2f1'}, spacing:'compact', headerStyle:'minimal', sectionOrder:['experience','skills','education','certifications','projects'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'square' },
  { id:'ats-7', name:'Harvard', category:'ats', atsScore:95, layout:'single', fonts:{heading:'Georgia, serif',body:'Times New Roman, serif'}, colors:{primary:'#8b0000',secondary:'#a51c1c',text:'#1a1a1a',muted:'#444',bg:'#fff',accent:'#fce4ec'}, spacing:'normal', headerStyle:'centered', sectionOrder:['summary','education','experience','skills','awards','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-8', name:'Oxford', category:'ats', atsScore:94, layout:'single', fonts:{heading:'Garamond, serif',body:'Garamond, serif'}, colors:{primary:'#002147',secondary:'#003366',text:'#1a1a1a',muted:'#444',bg:'#fff',accent:'#e3f2fd'}, spacing:'spacious', headerStyle:'left', sectionOrder:['summary','experience','education','skills','certifications','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-9', name:'Stanford', category:'ats', atsScore:93, layout:'single', fonts:{heading:'Palatino, serif',body:'Palatino, serif'}, colors:{primary:'#8c1515',secondary:'#b71c1c',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fbe9e7'}, spacing:'normal', headerStyle:'split', sectionOrder:['summary','experience','education','projects','skills','awards'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'dash' },
  { id:'ats-10', name:'Google', category:'ats', atsScore:95, layout:'single', fonts:{heading:'Roboto, sans-serif',body:'Roboto, sans-serif'}, colors:{primary:'#1a73e8',secondary:'#4285f4',text:'#202124',muted:'#5f6368',bg:'#fff',accent:'#e8f0fe'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','skills','education','projects','certifications'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'disc' },
  { id:'ats-11', name:'Microsoft', category:'ats', atsScore:94, layout:'single', fonts:{heading:'Segoe UI, sans-serif',body:'Segoe UI, sans-serif'}, colors:{primary:'#0078d4',secondary:'#106ebe',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#deecf9'}, spacing:'normal', headerStyle:'banner', sectionOrder:['summary','experience','skills','education','certifications','projects'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-12', name:'Amazon', category:'ats', atsScore:93, layout:'single', fonts:{heading:'Arial, sans-serif',body:'Arial, sans-serif'}, colors:{primary:'#ff9900',secondary:'#e68a00',text:'#0f1111',muted:'#555',bg:'#fff',accent:'#fff3e0'}, spacing:'compact', headerStyle:'left', sectionOrder:['summary','experience','projects','skills','education','certifications'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'arrow' },
  { id:'ats-13', name:'Meta', category:'ats', atsScore:94, layout:'single', fonts:{heading:'Helvetica Neue, sans-serif',body:'Helvetica Neue, sans-serif'}, colors:{primary:'#1877f2',secondary:'#166fe5',text:'#1c1e21',muted:'#606770',bg:'#fff',accent:'#e7f3ff'}, spacing:'normal', headerStyle:'minimal', sectionOrder:['summary','experience','projects','skills','education','languages'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'disc' },
  { id:'ats-14', name:'Apple', category:'ats', atsScore:96, layout:'single', fonts:{heading:'SF Pro Display, -apple-system, sans-serif',body:'SF Pro Text, -apple-system, sans-serif'}, colors:{primary:'#1d1d1f',secondary:'#333',text:'#1d1d1f',muted:'#6e6e73',bg:'#fff',accent:'#f5f5f7'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','skills','education','projects','certifications'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'dash' },
  { id:'ats-15', name:'QA Engineer', category:'ats', atsScore:95, layout:'single', fonts:{heading:'Consolas, monospace',body:'Calibri, sans-serif'}, colors:{primary:'#2e7d32',secondary:'#388e3c',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#e8f5e9'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','skills','experience','certifications','education','projects'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-16', name:'Software Engineer', category:'ats', atsScore:94, layout:'single', fonts:{heading:'Fira Code, monospace',body:'Inter, sans-serif'}, colors:{primary:'#6200ea',secondary:'#651fff',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#ede7f6'}, spacing:'normal', headerStyle:'split', sectionOrder:['summary','skills','experience','projects','education','certifications'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'arrow' },
  { id:'ats-17', name:'Developer', category:'ats', atsScore:93, layout:'single', fonts:{heading:'Source Code Pro, monospace',body:'Source Sans Pro, sans-serif'}, colors:{primary:'#00897b',secondary:'#00796b',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#e0f2f1'}, spacing:'compact', headerStyle:'left', sectionOrder:['skills','experience','projects','education','certifications','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'dash' },
  { id:'ats-18', name:'Product Manager', category:'ats', atsScore:95, layout:'single', fonts:{heading:'Lato, sans-serif',body:'Lato, sans-serif'}, colors:{primary:'#e65100',secondary:'#f57c00',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fff3e0'}, spacing:'normal', headerStyle:'centered', sectionOrder:['summary','experience','skills','education','certifications','awards'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-19', name:'Business Analyst', category:'ats', atsScore:94, layout:'single', fonts:{heading:'Merriweather, serif',body:'Open Sans, sans-serif'}, colors:{primary:'#37474f',secondary:'#455a64',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#eceff1'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','skills','education','certifications','projects'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-20', name:'Finance', category:'ats', atsScore:96, layout:'single', fonts:{heading:'Playfair Display, serif',body:'Lato, sans-serif'}, colors:{primary:'#1a237e',secondary:'#283593',text:'#1a1a1a',muted:'#444',bg:'#fff',accent:'#e8eaf6'}, spacing:'normal', headerStyle:'split', sectionOrder:['summary','experience','education','certifications','skills','awards'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-21', name:'Healthcare', category:'ats', atsScore:95, layout:'single', fonts:{heading:'Nunito, sans-serif',body:'Nunito, sans-serif'}, colors:{primary:'#0d47a1',secondary:'#1565c0',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#e3f2fd'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','education','certifications','skills','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-22', name:'Legal', category:'ats', atsScore:96, layout:'single', fonts:{heading:'Libre Baskerville, serif',body:'Libre Baskerville, serif'}, colors:{primary:'#3e2723',secondary:'#4e342e',text:'#1a1a1a',muted:'#444',bg:'#fff',accent:'#efebe9'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','education','certifications','awards','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-23', name:'Education', category:'ats', atsScore:94, layout:'single', fonts:{heading:'Crimson Text, serif',body:'Source Sans Pro, sans-serif'}, colors:{primary:'#bf360c',secondary:'#d84315',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fbe9e7'}, spacing:'normal', headerStyle:'left', sectionOrder:['education','experience','skills','certifications','projects','awards'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'ats-24', name:'Minimal ATS', category:'ats', atsScore:98, layout:'single', fonts:{heading:'Helvetica, sans-serif',body:'Helvetica, sans-serif'}, colors:{primary:'#212121',secondary:'#424242',text:'#1a1a1a',muted:'#757575',bg:'#fff',accent:'#fafafa'}, spacing:'compact', headerStyle:'minimal', sectionOrder:['experience','skills','education','certifications'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'dash' },
  { id:'ats-25', name:'International ATS', category:'ats', atsScore:93, layout:'single', fonts:{heading:'Noto Sans, sans-serif',body:'Noto Sans, sans-serif'}, colors:{primary:'#004d40',secondary:'#00695c',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#e0f2f1'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','education','skills','languages','certifications'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
];

// 25 Attractive Templates
const attractiveTemplates: TemplateConfig[] = [
  { id:'att-1', name:'Canva Style', category:'attractive', atsScore:82, layout:'sidebar-left', fonts:{heading:'Montserrat, sans-serif',body:'Open Sans, sans-serif'}, colors:{primary:'#7c3aed',secondary:'#a78bfa',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#f3e8ff',sidebarBg:'#7c3aed',sidebarText:'#fff'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','education','skills','projects','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'arrow' },
  { id:'att-2', name:'Creative', category:'attractive', atsScore:78, layout:'sidebar-left', fonts:{heading:'Poppins, sans-serif',body:'Poppins, sans-serif'}, colors:{primary:'#e91e63',secondary:'#f06292',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fce4ec',sidebarBg:'#1a1a2e',sidebarText:'#eee'}, spacing:'normal', headerStyle:'banner', sectionOrder:['summary','experience','projects','skills','education','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'arrow' },
  { id:'att-3', name:'Premium', category:'attractive', atsScore:85, layout:'sidebar-right', fonts:{heading:'Playfair Display, serif',body:'Raleway, sans-serif'}, colors:{primary:'#b8860b',secondary:'#d4a017',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fff8e1',sidebarBg:'#1a1a1a',sidebarText:'#ddd'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','education','skills','certifications','awards','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'dash' },
  { id:'att-4', name:'Luxury', category:'attractive', atsScore:80, layout:'sidebar-left', fonts:{heading:'Cormorant Garamond, serif',body:'Proza Libre, sans-serif'}, colors:{primary:'#1a1a1a',secondary:'#333',text:'#1a1a1a',muted:'#555',bg:'#fffdf7',accent:'#f5f0e8',sidebarBg:'#1a1a1a',sidebarText:'#d4af37'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','education','skills','awards','certifications','languages'], showPhoto:true, showIcons:false, borderStyle:'line', bulletStyle:'dash' },
  { id:'att-5', name:'Portfolio', category:'attractive', atsScore:76, layout:'sidebar-left', fonts:{heading:'Archivo, sans-serif',body:'Inter, sans-serif'}, colors:{primary:'#2196f3',secondary:'#64b5f6',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#e3f2fd',sidebarBg:'#0d47a1',sidebarText:'#fff'}, spacing:'normal', headerStyle:'banner', sectionOrder:['summary','projects','experience','skills','education','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'disc' },
  { id:'att-6', name:'Timeline', category:'attractive', atsScore:79, layout:'single', fonts:{heading:'Rubik, sans-serif',body:'Rubik, sans-serif'}, colors:{primary:'#6366f1',secondary:'#818cf8',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#eef2ff'}, spacing:'normal', headerStyle:'centered', sectionOrder:['summary','experience','education','projects','skills','certifications','languages'], showPhoto:false, showIcons:true, borderStyle:'dots', bulletStyle:'arrow' },
  { id:'att-7', name:'Modern Gradient', category:'attractive', atsScore:81, layout:'sidebar-left', fonts:{heading:'DM Sans, sans-serif',body:'DM Sans, sans-serif'}, colors:{primary:'#667eea',secondary:'#764ba2',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#eef2ff',sidebarBg:'linear-gradient(135deg,#667eea,#764ba2)',sidebarText:'#fff'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','skills','education','projects','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'disc' },
  { id:'att-8', name:'Dark Mode', category:'attractive', atsScore:77, layout:'sidebar-right', fonts:{heading:'Space Grotesk, sans-serif',body:'Space Grotesk, sans-serif'}, colors:{primary:'#a78bfa',secondary:'#c4b5fd',text:'#e2e8f0',muted:'#94a3b8',bg:'#0f172a',accent:'#1e293b',sidebarBg:'#1e293b',sidebarText:'#e2e8f0'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','skills','projects','education','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'arrow' },
  { id:'att-9', name:'Purple', category:'attractive', atsScore:83, layout:'sidebar-left', fonts:{heading:'Outfit, sans-serif',body:'Outfit, sans-serif'}, colors:{primary:'#7c3aed',secondary:'#a78bfa',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#ede9fe',sidebarBg:'#4c1d95',sidebarText:'#e9d5ff'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','education','skills','projects','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'disc' },
  { id:'att-10', name:'Blue Professional', category:'attractive', atsScore:86, layout:'sidebar-right', fonts:{heading:'Inter, sans-serif',body:'Inter, sans-serif'}, colors:{primary:'#1d4ed8',secondary:'#3b82f6',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#dbeafe',sidebarBg:'#1e3a5f',sidebarText:'#bfdbfe'}, spacing:'normal', headerStyle:'split', sectionOrder:['summary','experience','education','skills','certifications','projects','languages'], showPhoto:true, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'att-11', name:'Green', category:'attractive', atsScore:82, layout:'sidebar-left', fonts:{heading:'Nunito Sans, sans-serif',body:'Nunito Sans, sans-serif'}, colors:{primary:'#059669',secondary:'#34d399',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#d1fae5',sidebarBg:'#064e3b',sidebarText:'#a7f3d0'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','skills','education','projects','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'disc' },
  { id:'att-12', name:'Orange', category:'attractive', atsScore:80, layout:'sidebar-right', fonts:{heading:'Josefin Sans, sans-serif',body:'Lato, sans-serif'}, colors:{primary:'#ea580c',secondary:'#fb923c',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fff7ed',sidebarBg:'#7c2d12',sidebarText:'#fed7aa'}, spacing:'normal', headerStyle:'banner', sectionOrder:['summary','experience','education','skills','projects','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'arrow' },
  { id:'att-13', name:'Red Accent', category:'attractive', atsScore:81, layout:'single', fonts:{heading:'Bitter, serif',body:'Source Sans Pro, sans-serif'}, colors:{primary:'#dc2626',secondary:'#ef4444',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fef2f2'}, spacing:'normal', headerStyle:'split', sectionOrder:['summary','experience','education','skills','certifications','projects','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'disc' },
  { id:'att-14', name:'Gold', category:'attractive', atsScore:79, layout:'sidebar-left', fonts:{heading:'Cormorant, serif',body:'Fira Sans, sans-serif'}, colors:{primary:'#92400e',secondary:'#d97706',text:'#1a1a1a',muted:'#555',bg:'#fffbeb',accent:'#fef3c7',sidebarBg:'#451a03',sidebarText:'#fcd34d'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','education','skills','awards','certifications','languages'], showPhoto:true, showIcons:false, borderStyle:'none', bulletStyle:'dash' },
  { id:'att-15', name:'Startup', category:'attractive', atsScore:80, layout:'sidebar-right', fonts:{heading:'Sora, sans-serif',body:'Inter, sans-serif'}, colors:{primary:'#0ea5e9',secondary:'#38bdf8',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#e0f2fe',sidebarBg:'#0c4a6e',sidebarText:'#bae6fd'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','skills','experience','projects','education','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'arrow' },
  { id:'att-16', name:'Magazine', category:'attractive', atsScore:75, layout:'sidebar-left', fonts:{heading:'Abril Fatface, serif',body:'Lora, serif'}, colors:{primary:'#1a1a1a',secondary:'#333',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#f5f5f5',sidebarBg:'#fafafa',sidebarText:'#1a1a1a'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','education','projects','skills','certifications','languages'], showPhoto:true, showIcons:false, borderStyle:'line', bulletStyle:'dash' },
  { id:'att-17', name:'Neo Brutalism', category:'attractive', atsScore:74, layout:'single', fonts:{heading:'Space Mono, monospace',body:'Work Sans, sans-serif'}, colors:{primary:'#000',secondary:'#333',text:'#000',muted:'#333',bg:'#fff',accent:'#ffde59'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','skills','projects','education','certifications','languages'], showPhoto:false, showIcons:false, borderStyle:'line', bulletStyle:'square' },
  { id:'att-18', name:'Elegant', category:'attractive', atsScore:84, layout:'sidebar-right', fonts:{heading:'Cinzel, serif',body:'EB Garamond, serif'}, colors:{primary:'#4a2c2a',secondary:'#6d4c41',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#efebe9',sidebarBg:'#3e2723',sidebarText:'#d7ccc8'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['summary','experience','education','awards','skills','certifications','languages'], showPhoto:true, showIcons:false, borderStyle:'none', bulletStyle:'dash' },
  { id:'att-19', name:'Corporate Premium', category:'attractive', atsScore:87, layout:'sidebar-left', fonts:{heading:'Barlow, sans-serif',body:'Barlow, sans-serif'}, colors:{primary:'#1e3a5f',secondary:'#2563eb',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#f0f4ff',sidebarBg:'#1e3a5f',sidebarText:'#dbeafe'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','education','skills','certifications','projects','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'disc' },
  { id:'att-20', name:'Professional Designer', category:'attractive', atsScore:79, layout:'sidebar-left', fonts:{heading:'Manrope, sans-serif',body:'Manrope, sans-serif'}, colors:{primary:'#ec4899',secondary:'#f472b6',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#fdf2f8',sidebarBg:'#831843',sidebarText:'#fbcfe8'}, spacing:'normal', headerStyle:'banner', sectionOrder:['summary','projects','experience','skills','education','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'arrow' },
  { id:'att-21', name:'Minimal Color', category:'attractive', atsScore:85, layout:'single', fonts:{heading:'Plus Jakarta Sans, sans-serif',body:'Plus Jakarta Sans, sans-serif'}, colors:{primary:'#0d9488',secondary:'#14b8a6',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#ccfbf1'}, spacing:'normal', headerStyle:'minimal', sectionOrder:['summary','experience','education','skills','projects','certifications','languages'], showPhoto:false, showIcons:false, borderStyle:'none', bulletStyle:'dash' },
  { id:'att-22', name:'Creative Blocks', category:'attractive', atsScore:76, layout:'sidebar-right', fonts:{heading:'Lexend, sans-serif',body:'Lexend, sans-serif'}, colors:{primary:'#7c3aed',secondary:'#a78bfa',text:'#1a1a1a',muted:'#555',bg:'#faf5ff',accent:'#ede9fe',sidebarBg:'#5b21b6',sidebarText:'#e9d5ff'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','skills','experience','projects','education','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'disc' },
  { id:'att-23', name:'Designer CV', category:'attractive', atsScore:77, layout:'sidebar-left', fonts:{heading:'Clash Display, sans-serif',body:'Satoshi, sans-serif'}, colors:{primary:'#1a1a1a',secondary:'#333',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#f0f0f0',sidebarBg:'#f0f0f0',sidebarText:'#1a1a1a'}, spacing:'spacious', headerStyle:'centered', sectionOrder:['projects','experience','skills','education','awards','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'dash' },
  { id:'att-24', name:'Resume Pro', category:'attractive', atsScore:84, layout:'sidebar-right', fonts:{heading:'Albert Sans, sans-serif',body:'Albert Sans, sans-serif'}, colors:{primary:'#4338ca',secondary:'#6366f1',text:'#1a1a1a',muted:'#555',bg:'#fff',accent:'#eef2ff',sidebarBg:'#312e81',sidebarText:'#c7d2fe'}, spacing:'normal', headerStyle:'split', sectionOrder:['summary','experience','education','skills','certifications','projects','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'disc' },
  { id:'att-25', name:'Glassmorphism', category:'attractive', atsScore:73, layout:'sidebar-left', fonts:{heading:'General Sans, sans-serif',body:'General Sans, sans-serif'}, colors:{primary:'#8b5cf6',secondary:'#a78bfa',text:'#1a1a1a',muted:'#555',bg:'#f8fafc',accent:'rgba(139,92,246,0.1)',sidebarBg:'rgba(139,92,246,0.08)',sidebarText:'#1a1a1a'}, spacing:'normal', headerStyle:'left', sectionOrder:['summary','experience','skills','projects','education','certifications','languages'], showPhoto:true, showIcons:true, borderStyle:'none', bulletStyle:'arrow' },
];

export const ALL_TEMPLATES: TemplateConfig[] = [...atsTemplates, ...attractiveTemplates];

export function getTemplateById(id: string): TemplateConfig | undefined {
  return ALL_TEMPLATES.find(t => t.id === id);
}

export function getTemplatesByCategory(category: 'ats' | 'attractive'): TemplateConfig[] {
  return ALL_TEMPLATES.filter(t => t.category === category);
}
